In [2]:
import pandas as pd
import numpy as np
autos = pd.read_csv('autos.csv', encoding = 'Latin-1')

In [3]:
autos

,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,odometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,"$8,500",control,limousine,1997,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,"$8,990",test,limousine,2009,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,"$4,350",control,kleinwagen,2007,automatik,71,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,privat,Angebot,"$1,350",test,kombi,2003,manuell,0,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50
5,2016-03-21 13:47:45,Chrysler_Grand_Voyager_2.8_CRD_Aut.Limited_Sto...,privat,Angebot,"$7,900",test,bus,2006,automatik,150,voyager,"150,000km",4,diesel,chrysler,NaN,2016-03-21 00:00:00,0,22962,2016-04-06 09:45:21
6,2016-03-20 17:55:21,VW_Golf_III_GT_Special_Electronic_Green_Metall...,privat,Angebot,$300,test,limousine,1995,manuell,90,golf,"150,000km",8,benzin,volkswagen,NaN,2016-03-20 00:00:00,0,31535,2016-03-23 02:48:59
7,2016-03-16 18:55:19,Golf_IV_1.9_TDI_90PS,privat,Angebot,"$1,990",control,limousine,1998,manuell,90,golf,"150,000km",12,diesel,volkswagen,nein,2016-03-16 00:00:00,0,53474,2016-04-07 03:17:32
8,2016-03-22 16:51:34,Seat_Arosa,privat,Angebot,$250,test,NaN,2000,manuell,0,arosa,"150,000km",10,NaN,seat,nein,2016-03-22 00:00:00,0,7426,2016-03-26 18:18:10
9,2016-03-16 13:47:02,Renault_Megane_Scenic_1.6e_RT_Klimaanlage,privat,Angebot,$590,control,bus,1997,manuell,90,megane,"150,000km",7,benzin,renault,nein,2016-03-16 00:00:00,0,15749,2016-04-06 10:46:35
10,2016-03-15 01:41:36,VW_Golf_Tuning_in_siber/grau,privat,Angebot,$999,test,NaN,2017,manuell,90,NaN,"150,000km",4,benzin,volkswagen,nein,2016-03-14 00:00:00,0,86157,2016-04-07 03:16:21
11,2016-03-16 18:45:34,Mercedes_A140_Motorschaden,privat,Angebot,$350,control,NaN,2000,NaN,0,NaN,"150,000km",0,benzin,mercedes_benz,NaN,2016-03-16 00:00:00,0,17498,2016-03-16 18:45:34
12,2016-03-31 19:48:22,Smart_smart_fortwo_coupe_softouch_pure_MHD_Pan...,privat,Angebot,"$5,299",control,kleinwagen,2010,automatik,71,fortwo,"50,000km",9,benzin,smart,nein,2016-03-31 00:00:00,0,34590,2016-04-06 14:17:52
13,2016-03-23 10:48:32,Audi_A3_1.6_tuning,privat,Angebot,"$1,350",control,limousine,1999,manuell,101,a3,"150,000km",11,benzin,audi,nein,2016-03-23 00:00:00,0,12043,2016-04-01 14:17:13
14,2016-03-23 11:50:46,Renault_Clio_3__Dynamique_1.2__16_V;_viele_Ver...,privat,Angebot,"$3,999",test,kleinwagen,2007,manuell,75,clio,"150,000km",9,benzin,renault,NaN,2016-03-23 00:00:00,0,81737,2016-04-01 15:46:47
15,2016-04-01 12:06:20,Corvette_C3_Coupe_T_Top_Crossfire_Injection,privat,Angebot,"$18,900",test,coupe,1982,automatik,203,NaN,"80,000km",6,benzin,sonstige_autos,nein,2016-04-01 00:00:00,0,61276,2016-04-02 21:10:48
16,2016-03-16 14:59:02,Opel_Vectra_B_Kombi,privat,Angebot,$350,test,kombi,1999,manuell,101,vectra,"150,000km",5,benzin,opel,nein,2016-03-16 00:00:00,0,57299,2016-03-18 05:29:37
17,2016-03-29 11:46:22,Volkswagen_Scirocco_2_G60,privat,Angebot,"$5,500",test,coupe,1990,manuell,205,scirocco,"150,000km",6,benzin,volkswagen,nein,2016-03-29 00:00:00,0,74821,2016-04-05 20:46:26
18,2016-03-26 19:57:44,Verkaufen_mein_bmw_e36_320_i_touring,privat,Angebot,$300,control,bus,1995,manuell,150,3er,"150,000km",0,benzin,bmw,NaN,2016-03-26 00:00:00,0,54329,2016-04-02 12:16:41
19,2016-03-17 13:36:21,mazda_tribute_2.0_mit_gas_und_tuev_neu_2018,privat,Angebot,"$4,150",control,suv,2004,manuell,124,andere,"150,000km",2,lpg,mazda,nein,2016-03-17 00:00:00,0,40878,2016-03-17 14:45:58
20,2016-03-05 19:57:31,Audi_A4_Avant_1.9_TDI_*6_Gang*AHK*Klimatronik*...,privat,Angebot,"$3,500",test,kombi,2003,manuell,131,a4,"150,000km",5,diesel,audi,NaN,2016-03-05 00:00:00,0,53913,2016-03-07 05:46:46
21,2016-03-06 19:07:10,Porsche_911_Carrera_4S_Cabrio,privat,Angebot,"$41,500",test,cabrio,2004,manuell,320,911,"150,000km",4,benzin,porsche,nein,2016-03-06 00:00:00,0,65428,2016-04-05 23:46:19
22,2016-03-28 20:50:54,MINI_Cooper_S_Cabrio,privat,Angebot,"$25,450",control,cabrio,2015,manuell,184,cooper,"10,000km",1,benzin,mini,nein,2016-03-28 00:00:00,0,44789,2016-04-01 06:45:30
23,2016-03-10 19:55:34,Peugeot_Boxer_2_2_HDi_120_Ps_9_Sitzer_inkl_Klima,privat,Angebot,"$7,999",control,bus,2010,manuell,120,NaN,"150,000km",2,diesel,peugeot,nein,2016-03-10 00:00:00,0,30900,2016-03-17 08:45:17
24,2016-04-03 11:57:02,BMW_535i_xDrive_Sport_Aut.,privat,Angebot,"$48,500",control,limousine,2014,automatik,306,5er,"30,000km",12,benzin,bmw,nein,2016-04-03 00:00:00,0,22547,2016-04-07 13:16:50
25,2016-03-21 21:56:18,Ford_escort_kombi_an_bastler_mit_ghia_ausstattung,privat,Angebot,$90,control,kombi,1996,manuell,116,NaN,"150,000km",4,benzin,ford,ja,2016-03-21 00:00:00,0,27574,2016-04-01 05:16:49
26,2016-04-03 22:46:28,Volkswagen_Polo_Fox,privat,Angebot,$777,control,kleinwagen,1992,manuell,54,polo,"125,000km",2,benzin,volkswagen,nein,2016-04-03 00:00:00,0,38110,2016-04-05 23:46:48
27,2016-03-27 18:45:01,Hat_einer_Ahnung_mit_Ford_Galaxy_HILFE,privat,Angebot,$0,control,NaN,2005,NaN,0,NaN,"150,000km",0,NaN,ford,NaN,2016-03-27 00:00:00,0,66701,2016-03-27 18:45:01
28,2016-03-19 21:56:19,MINI_Cooper_D,privat,Angebot,"$5,250",control,kleinwagen,2007,manuell,110,cooper,"150,000km",7,diesel,mini,ja,2016-03-19 00:00:00,0,15745,2016-04-07 14:58:48
29,2016-04-02 12:45:44,Mercedes_Benz_E_320_T_CDI_Avantgarde_DPF7_Sitz...,privat,Angebot,"$4,999",test,kombi,2004,automatik,204,e_klasse,"150,000km",10,diesel,mercedes_benz,nein,2016-04-02 00:00:00,0,47638,2016-04-02 12:45:44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49970,2016-03-21 22:47:37,c4_Grand_Picasso_mit_Automatik_Leder_Navi_Temp...,privat,Angebot,"$15,800",control,bus,2010,automatik,136,c4,"60,000km",4,diesel,citroen,nein,2016-03-21 00:00:00,0,14947,2016-04-07 04:17:34
49971,2016-03-29 14:54:12,W.Lupo_1.0,privat,Angebot,$950,test,kleinwagen,2001,manuell,50,lupo,"150,000km",4,benzin,volkswagen,nein,2016-03-29 00:00:00,0,65197,2016-03-29 20:41:51
49972,2016-03-26 22:25:23,Mercedes_Benz_Vito_115_CDI_Extralang_Aut.,privat,Angebot,"$3,300",control,bus,2004,automatik,150,vito,"150,000km",10,diesel,mercedes_benz,ja,2016-03-26 00:00:00,0,65326,2016-03-28 11:28:18
49973,2016-03-27 05:32:39,Mercedes_Benz_SLK_200_Kompressor,privat,Angebot,"$6,000",control,cabrio,2004,manuell,163,slk,"150,000km",11,benzin,mercedes_benz,nein,2016-03-27 00:00:00,0,53567,2016-03-27 08:25:24
49974,2016-03-20 10:52:31,Golf_1_Cabrio_Tuev_Neu_viele_Extras_alles_eing...,privat,Angebot,$0,control,cabrio,1983,manuell,70,golf,"150,000km",2,benzin,volkswagen,nein,2016-03-20 00:00:00,0,8209,2016-03-27 19:48:16
49975,2016-03-27 20:51:39,Honda_Jazz_1.3_DSi_i_VTEC_IMA_CVT_Comfort,privat,Angebot,"$9,700",control,kleinwagen,2012,automatik,88,jazz,"100,000km",11,hybrid,honda,nein,2016-03-27 00:00:00,0,84385,2016-04-05 19:45:34
49976,2016-03-19 18:56:05,Audi_80_Avant_2.6_E__Vollausstattung!!_Einziga...,privat,Angebot,"$5,900",test,kombi,1992,automatik,150,80,"150,000km",12,benzin,audi,nein,2016-03-19 00:00:00,0,36100,2016-04-07 06:16:44
49977,2016-03-31 18:37:18,Mercedes_Benz_C200_Cdi_W203,privat,Angebot,"$5,500",control,limousine,2003,manuell,116,c_klasse,"150,000km",2,diesel,mercedes_benz,nein,2016-03-31 00:00:00,0,33739,2016-04-06 12:16:11
49978,2016-04-04 10:37:14,Mercedes_Benz_E_200_Classic,privat,Angebot,$900,control,limousine,1996,automatik,136,e_klasse,"150,000km",9,benzin,mercedes_benz,ja,2016-04-04 00:00:00,0,24405,2016-04-06 12:44:20
49979,2016-03-20 18:38:40,Volkswagen_Polo_1.6_TDI_Style,privat,Angebot,"$11,000",test,kleinwagen,2011,manuell,90,polo,"70,000km",11,diesel,volkswagen,nein,2016-03-20 00:00:00,0,48455,2016-04-07 01:45:12
49980,2016-03-12 10:55:54,Ford_Escort_Turnier_16V,privat,Angebot,$400,control,kombi,1995,manuell,105,escort,"125,000km",3,benzin,ford,NaN,2016-03-12 00:00:00,0,56218,2016-04-06 17:16:49
49981,2016-03-15 09:38:21,Opel_Astra_Kombi_mit_Anhaengerkupplung,privat,Angebot,"$2,000",control,kombi,1998,manuell,115,astra,"150,000km",12,benzin,opel,nein,2016-03-15 00:00:00,0,86859,2016-04-05 17:21:46
49982,2016-03-29 18:51:08,Skoda_Fabia_4_Tuerer_Bj:2004__85.000Tkm,privat,Angebot,"$1,950",control,kleinwagen,2004,manuell,0,fabia,"90,000km",7,benzin,skoda,NaN,2016-03-29 00:00:00,0,45884,2016-03-29 18:51:08
49983,2016-03-06 12:43:04,Ford_focus_99,privat,Angebot,$600,test,kleinwagen,1999,manuell,101,focus,"150,000km",4,benzin,ford,NaN,2016-03-06 00:00:00,0,52477,2016-03-09 06:16:08
49984,2016-03-31 22:48:48,Student_sucht_ein__Anfaengerauto___ab_2000_BJ_...,privat,Angebot,$0,test,NaN,2000,NaN,0,NaN,"150,000km",0,NaN,sonstige_autos,NaN,2016-03-31 00:00:00,0,12103,2016-04-02 19:44:53
49985,2016-04-02 16:38:23,Verkaufe_meinen_vw_vento!,privat,Angebot,"$1,000",control,NaN,1995,automatik,0,NaN,"150,000km",0,benzin,volkswagen,NaN,2016-04-02 00:00:00,0,30900,2016-04-06 15:17:52
49986,2016-04-04 20:46:02,Chrysler_300C_3.0_CRD_DPF_Automatik_Voll_Ausst...,privat,Angebot,"$15,900",control,limousine,2010,automatik,218,300c,"125,000km",11,diesel,chrysler,nein,2016-04-04 00:00:00,0,73527,2016-04-06 23:16:00
49987,2016-03-22 20:47:27,Audi_A3_Limousine_2.0_TDI_DPF_Ambition__NAVI__...,privat,Angebot,"$21,990",control,limousine,2013,manuell,150,a3,"50,000km",11,diesel,audi,nein,2016-03-22 00:00:00,0,94362,2016-03-26 22:46:06
49988,2016-03-28 19:49:51,BMW_330_Ci,privat,Angebot,"$9,550",control,coupe,2001,manuell,231,3er,"150,000km",10,benzin,bmw,nein,2016-03-28 00:00:00,0,83646,2016-04-07 02:17:40
49989,2016-03-11 19:50:37,VW_Polo_zum_Ausschlachten_oder_Wiederaufbau,privat,Angebot,$150,test,kleinwagen,1997,manuell,0,polo,"150,000km",5,benzin,volkswagen,ja,2016-03-11 00:00:00,0,21244,2016-03-12 10:17:55
49990,2016-03-21 19:54:19,Mercedes_Benz_A_200__BlueEFFICIENCY__Urban,privat,Angebot,"$17,500",test,limousine,2012,manuell,156,a_klasse,"30,000km",12,benzin,mercedes_benz,nein,2016-03-21 00:00:00,0,58239,2016-04-06 22:46:57
49991,2016-03-06 15:25:19,Kleinwagen,privat,Angebot,$500,control,NaN,2016,manuell,0,twingo,"150,000km",0,benzin,renault,NaN,2016-03-06 00:00:00,0,61350,2016-03-06 18:24:19
49992,2016-03-10 19:37:38,Fiat_Grande_Punto_1.4_T_Jet_16V_Sport,privat,Angebot,"$4,800",control,kleinwagen,2009,manuell,120,andere,"125,000km",9,lpg,fiat,nein,2016-03-10 00:00:00,0,68642,2016-03-13 01:44:51
49993,2016-03-15 18:47:35,Audi_A3__1_8l__Silber;_schoenes_Fahrzeug,privat,Angebot,"$1,650",control,kleinwagen,1997,manuell,0,NaN,"150,000km",7,benzin,audi,NaN,2016-03-15 00:00:00,0,65203,2016-04-06 19:46:53
49994,2016-03-22 17:36:42,Audi_A6__S6__Avant_4.2_quattro_eventuell_Tausc...,privat,Angebot,"$5,000",control,kombi,2001,automatik,299,a6,"150,000km",1,benzin,audi,nein,2016-03-22 00:00:00,0,46537,2016-04-06 08:16:39
49995,2016-03-27 14:38:19,Audi_Q5_3.0_TDI_qu._S_tr.__Navi__Panorama__Xenon,privat,Angebot,"$24,900",control,limousine,2011,automatik,239,q5,"100,000km",1,diesel,audi,nein,2016-03-27 00:00:00,0,82131,2016-04-01 13:47:40
49996,2016-03-28 10:50:25,Opel_Astra_F_Cabrio_Bertone_Edition___TÃœV_neu+...,privat,Angebot,"$1,980",control,cabrio,1996,manuell,75,astra,"150,000km",5,benzin,opel,nein,2016-03-28 00:00:00,0,44807,2016-04-02 14:18:02
49997,2016-04-02 14:44:48,Fiat_500_C_1.2_Dualogic_Lounge,privat,Angebot,"$13,200",test,cabrio,2014,automatik,69,500,"5,000km",11,benzin,fiat,nein,2016-04-02 00:00:00,0,73430,2016-04-04 11:47:27
49998,2016-03-08 19:25:42,Audi_A3_2.0_TDI_Sportback_Ambition,privat,Angebot,"$22,900",control,kombi,2013,manuell,150,a3,"40,000km",11,diesel,audi,nein,2016-03-08 00:00:00,0,35683,2016-04-05 16:45:07
49999,2016-03-14 00:42:12,Opel_Vectra_1.6_16V,privat,Angebot,"$1,250",control,limousine,1996,manuell,101,vectra,"150,000km",1,benzin,opel,nein,2016-03-13 00:00:00,0,45897,2016-04-06 21:18:48

In [4]:
autos.info()
autos.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 20 columns):
dateCrawled            50000 non-null object
name                   50000 non-null object
seller                 50000 non-null object
offerType              50000 non-null object
price                  50000 non-null object
abtest                 50000 non-null object
vehicleType            44905 non-null object
yearOfRegistration     50000 non-null int64
gearbox                47320 non-null object
powerPS                50000 non-null int64
model                  47242 non-null object
odometer               50000 non-null object
monthOfRegistration    50000 non-null int64
fuelType               45518 non-null object
brand                  50000 non-null object
notRepairedDamage      40171 non-null object
dateCreated            50000 non-null object
nrOfPictures           50000 non-null int64
postalCode             50000 non-null int64
lastSeen               50000 non-null object
dtypes: int64(5), object(15)
memory usage: 7.6+ MB

,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,odometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,"$8,500",control,limousine,1997,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,"$8,990",test,limousine,2009,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,"$4,350",control,kleinwagen,2007,automatik,71,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,privat,Angebot,"$1,350",test,kombi,2003,manuell,0,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50

price, odometer, date created, lastseen columns needed to change from object to numeric

In [5]:
autos_col = autos.columns
print(autos_col)

Index(['dateCrawled', 'name', 'seller', 'offerType', 'price', 'abtest',
       'vehicleType', 'yearOfRegistration', 'gearbox', 'powerPS', 'model',
       'odometer', 'monthOfRegistration', 'fuelType', 'brand',
       'notRepairedDamage', 'dateCreated', 'nrOfPictures', 'postalCode',
       'lastSeen'],
      dtype='object')

In [6]:
new_col = ['date_crawled', 'name', 'seller', 'offer_type', 'price', 'abtest',
       'vehicle_type', 'registration_year', 'gear_box', 'power_ps', 'model',
       'odometer', 'registration_month', 'fuel_type', 'brand',
       'unrepaired_damage', 'ad_created', 'nr_of_pictures', 'postal_code',
       'last_seen']
autos.columns = new_col

In [7]:
print(autos.columns)

Index(['date_crawled', 'name', 'seller', 'offer_type', 'price', 'abtest',
       'vehicle_type', 'registration_year', 'gear_box', 'power_ps', 'model',
       'odometer', 'registration_month', 'fuel_type', 'brand',
       'unrepaired_damage', 'ad_created', 'nr_of_pictures', 'postal_code',
       'last_seen'],
      dtype='object')

In [8]:
autos.head()

,date_crawled,name,seller,offer_type,price,abtest,vehicle_type,registration_year,gear_box,power_ps,model,odometer,registration_month,fuel_type,brand,unrepaired_damage,ad_created,nr_of_pictures,postal_code,last_seen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,"$8,500",control,limousine,1997,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,"$8,990",test,limousine,2009,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,"$4,350",control,kleinwagen,2007,automatik,71,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,privat,Angebot,"$1,350",test,kombi,2003,manuell,0,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50

In [9]:
autos.describe()

,registration_year,power_ps,registration_month,nr_of_pictures,postal_code
count,50000.000000,50000.000000,50000.000000,50000.0,50000.000000
mean,2005.073280,116.355920,5.723360,0.0,50813.627300
std,105.712813,209.216627,3.711984,0.0,25779.747957
min,1000.000000,0.000000,0.000000,0.0,1067.000000
25%,1999.000000,70.000000,3.000000,0.0,30451.000000
50%,2003.000000,105.000000,6.000000,0.0,49577.000000
75%,2008.000000,150.000000,9.000000,0.0,71540.000000
max,9999.000000,17700.000000,12.000000,0.0,99998.000000

any columns that have mostly one value that are candidates to be dropped
any columns that need more investigation
any examples of numeric data stored as text that needs to be cleaned

In [10]:
autos['price'] = (autos['price'].apply(str).str.replace('$','').str.replace(',','').astype(float))
autos['odometer'] = (autos['odometer'].apply(str).str.replace('km','').str.replace(',','').astype(float))

autos.head()

,date_crawled,name,seller,offer_type,price,abtest,vehicle_type,registration_year,gear_box,power_ps,model,odometer,registration_month,fuel_type,brand,unrepaired_damage,ad_created,nr_of_pictures,postal_code,last_seen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,5000.0,control,bus,2004,manuell,158,andere,150000.0,3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,8500.0,control,limousine,1997,automatik,286,7er,150000.0,6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,8990.0,test,limousine,2009,manuell,102,golf,70000.0,7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,4350.0,control,kleinwagen,2007,automatik,71,fortwo,70000.0,6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,privat,Angebot,1350.0,test,kombi,2003,manuell,0,focus,150000.0,7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50

In [11]:
autos.rename({'odometer': 'odometer_km'}, axis = 1, inplace =True)

In [12]:
autos['odometer_km'].head()

0    150000.0
1    150000.0
2     70000.0
3     70000.0
4    150000.0
Name: odometer_km, dtype: float64

In [13]:
print(autos['price'].unique().shape)
print(autos['odometer_km'].unique().shape)

(2357,)
(13,)

In [14]:
autos['price'].describe()

count    5.000000e+04
mean     9.840044e+03
std      4.811044e+05
min      0.000000e+00
25%      1.100000e+03
50%      2.950000e+03
75%      7.200000e+03
max      1.000000e+08
Name: price, dtype: float64

In [15]:
autos['odometer_km'].describe()

count     50000.000000
mean     125732.700000
std       40042.211706
min        5000.000000
25%      125000.000000
50%      150000.000000
75%      150000.000000
max      150000.000000
Name: odometer_km, dtype: float64

In [16]:
autos['price'].value_counts().sort_index(ascending = False).head(20)

99999999.0    1
27322222.0    1
12345678.0    3
11111111.0    2
10000000.0    1
3890000.0     1
1300000.0     1
1234566.0     1
999999.0      2
999990.0      1
350000.0      1
345000.0      1
299000.0      1
295000.0      1
265000.0      1
259000.0      1
250000.0      1
220000.0      1
198000.0      1
197000.0      1
Name: price, dtype: int64

In [17]:
autos['odometer_km'].value_counts().sort_index()

5000.0        967
10000.0       264
20000.0       784
30000.0       789
40000.0       819
50000.0      1027
60000.0      1164
70000.0      1230
80000.0      1436
90000.0      1757
100000.0     2169
125000.0     5170
150000.0    32424
Name: odometer_km, dtype: int64

In [18]:
autos['price'].head()

0    5000.0
1    8500.0
2    8990.0
3    4350.0
4    1350.0
Name: price, dtype: float64

In [19]:
autos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 20 columns):
date_crawled          50000 non-null object
name                  50000 non-null object
seller                50000 non-null object
offer_type            50000 non-null object
price                 50000 non-null float64
abtest                50000 non-null object
vehicle_type          44905 non-null object
registration_year     50000 non-null int64
gear_box              47320 non-null object
power_ps              50000 non-null int64
model                 47242 non-null object
odometer_km           50000 non-null float64
registration_month    50000 non-null int64
fuel_type             45518 non-null object
brand                 50000 non-null object
unrepaired_damage     40171 non-null object
ad_created            50000 non-null object
nr_of_pictures        50000 non-null int64
postal_code           50000 non-null int64
last_seen             50000 non-null object
dtypes: float64(2), int64(5), object(13)
memory usage: 7.6+ MB

In [20]:
autos.loc[(autos['price'] > 350000), 'price'] = np.nan

In [21]:
autos.loc[autos['price'].isnull(), 'price'].shape

(14,)

In [22]:
autos.dropna()

,date_crawled,name,seller,offer_type,price,abtest,vehicle_type,registration_year,gear_box,power_ps,model,odometer_km,registration_month,fuel_type,brand,unrepaired_damage,ad_created,nr_of_pictures,postal_code,last_seen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,5000.0,control,bus,2004,manuell,158,andere,150000.0,3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,8500.0,control,limousine,1997,automatik,286,7er,150000.0,6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,8990.0,test,limousine,2009,manuell,102,golf,70000.0,7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,4350.0,control,kleinwagen,2007,automatik,71,fortwo,70000.0,6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,privat,Angebot,1350.0,test,kombi,2003,manuell,0,focus,150000.0,7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50
7,2016-03-16 18:55:19,Golf_IV_1.9_TDI_90PS,privat,Angebot,1990.0,control,limousine,1998,manuell,90,golf,150000.0,12,diesel,volkswagen,nein,2016-03-16 00:00:00,0,53474,2016-04-07 03:17:32
9,2016-03-16 13:47:02,Renault_Megane_Scenic_1.6e_RT_Klimaanlage,privat,Angebot,590.0,control,bus,1997,manuell,90,megane,150000.0,7,benzin,renault,nein,2016-03-16 00:00:00,0,15749,2016-04-06 10:46:35
12,2016-03-31 19:48:22,Smart_smart_fortwo_coupe_softouch_pure_MHD_Pan...,privat,Angebot,5299.0,control,kleinwagen,2010,automatik,71,fortwo,50000.0,9,benzin,smart,nein,2016-03-31 00:00:00,0,34590,2016-04-06 14:17:52
13,2016-03-23 10:48:32,Audi_A3_1.6_tuning,privat,Angebot,1350.0,control,limousine,1999,manuell,101,a3,150000.0,11,benzin,audi,nein,2016-03-23 00:00:00,0,12043,2016-04-01 14:17:13
16,2016-03-16 14:59:02,Opel_Vectra_B_Kombi,privat,Angebot,350.0,test,kombi,1999,manuell,101,vectra,150000.0,5,benzin,opel,nein,2016-03-16 00:00:00,0,57299,2016-03-18 05:29:37
17,2016-03-29 11:46:22,Volkswagen_Scirocco_2_G60,privat,Angebot,5500.0,test,coupe,1990,manuell,205,scirocco,150000.0,6,benzin,volkswagen,nein,2016-03-29 00:00:00,0,74821,2016-04-05 20:46:26
19,2016-03-17 13:36:21,mazda_tribute_2.0_mit_gas_und_tuev_neu_2018,privat,Angebot,4150.0,control,suv,2004,manuell,124,andere,150000.0,2,lpg,mazda,nein,2016-03-17 00:00:00,0,40878,2016-03-17 14:45:58
21,2016-03-06 19:07:10,Porsche_911_Carrera_4S_Cabrio,privat,Angebot,41500.0,test,cabrio,2004,manuell,320,911,150000.0,4,benzin,porsche,nein,2016-03-06 00:00:00,0,65428,2016-04-05 23:46:19
22,2016-03-28 20:50:54,MINI_Cooper_S_Cabrio,privat,Angebot,25450.0,control,cabrio,2015,manuell,184,cooper,10000.0,1,benzin,mini,nein,2016-03-28 00:00:00,0,44789,2016-04-01 06:45:30
24,2016-04-03 11:57:02,BMW_535i_xDrive_Sport_Aut.,privat,Angebot,48500.0,control,limousine,2014,automatik,306,5er,30000.0,12,benzin,bmw,nein,2016-04-03 00:00:00,0,22547,2016-04-07 13:16:50
26,2016-04-03 22:46:28,Volkswagen_Polo_Fox,privat,Angebot,777.0,control,kleinwagen,1992,manuell,54,polo,125000.0,2,benzin,volkswagen,nein,2016-04-03 00:00:00,0,38110,2016-04-05 23:46:48
28,2016-03-19 21:56:19,MINI_Cooper_D,privat,Angebot,5250.0,control,kleinwagen,2007,manuell,110,cooper,150000.0,7,diesel,mini,ja,2016-03-19 00:00:00,0,15745,2016-04-07 14:58:48
29,2016-04-02 12:45:44,Mercedes_Benz_E_320_T_CDI_Avantgarde_DPF7_Sitz...,privat,Angebot,4999.0,test,kombi,2004,automatik,204,e_klasse,150000.0,10,diesel,mercedes_benz,nein,2016-04-02 00:00:00,0,47638,2016-04-02 12:45:44
30,2016-03-14 11:47:31,Peugeot_206_Unfallfahrzeug,privat,Angebot,80.0,test,kleinwagen,2002,manuell,60,2_reihe,150000.0,6,benzin,peugeot,ja,2016-03-14 00:00:00,0,57076,2016-03-14 11:47:31
31,2016-03-14 16:53:09,Noch_gut_erhaltenen_C_320,privat,Angebot,2850.0,test,kombi,2002,automatik,218,c_klasse,150000.0,7,benzin,mercedes_benz,nein,2016-03-14 00:00:00,0,41065,2016-03-16 07:19:04
33,2016-03-15 12:25:26,Audi_A3_2.0_TDI_Sportback_DPF_Kupplung_defekt_...,privat,Angebot,4800.0,test,kombi,2006,manuell,140,a3,150000.0,8,diesel,audi,nein,2016-03-15 00:00:00,0,61169,2016-04-07 13:15:31
35,2016-03-29 21:52:56,Ford_Mondeo,privat,Angebot,1200.0,test,kombi,1998,manuell,0,mondeo,150000.0,12,benzin,ford,nein,2016-03-29 00:00:00,0,52428,2016-04-06 08:45:35
36,2016-03-16 23:46:31,Ford_Mondeo_2.0_Turnier_TDCi_DPF_Titanium,privat,Angebot,7500.0,test,kombi,2007,manuell,131,mondeo,150000.0,11,diesel,ford,nein,2016-03-16 00:00:00,0,34246,2016-04-05 16:21:16
37,2016-03-23 16:47:46,Seat_Altea_XL_2.0_TDI_CR_DPF_Style,privat,Angebot,13800.0,test,bus,2012,manuell,140,altea,90000.0,2,diesel,seat,nein,2016-03-23 00:00:00,0,85113,2016-04-05 20:17:53
38,2016-03-21 15:51:10,Volkswagen_Golf_1.4_Special,privat,Angebot,2850.0,control,limousine,2002,manuell,75,golf,125000.0,2,benzin,volkswagen,nein,2016-03-21 00:00:00,0,63674,2016-03-28 12:16:06
39,2016-03-11 13:58:38,Mercedes_C_180_Kombi__zu_verkaufen,privat,Angebot,1450.0,test,kombi,1999,automatik,122,c_klasse,150000.0,6,benzin,mercedes_benz,nein,2016-03-11 00:00:00,0,12683,2016-04-06 15:17:52
40,2016-03-07 14:50:03,VW_Golf__4_Cabrio_2.0_GTI_16V___Leder_MFA_Alus...,privat,Angebot,3500.0,control,cabrio,1999,manuell,150,golf,150000.0,1,benzin,volkswagen,nein,2016-03-07 00:00:00,0,6780,2016-03-12 02:15:52
43,2016-03-08 16:51:22,Audi_A1_1.2_TFSI_Attraction_mit_Garantie,privat,Angebot,11500.0,test,kleinwagen,2011,manuell,86,a1,60000.0,9,benzin,audi,nein,2016-03-08 00:00:00,0,85049,2016-04-07 03:16:05
44,2016-03-12 10:38:06,Zu_verkaufen,privat,Angebot,900.0,control,kleinwagen,1998,manuell,43,twingo,150000.0,7,benzin,renault,nein,2016-03-12 00:00:00,0,79725,2016-04-06 01:17:27
45,2016-03-12 17:39:55,Toyota_Starlet_1.3,privat,Angebot,1000.0,test,kleinwagen,1995,manuell,75,andere,150000.0,3,benzin,toyota,nein,2016-03-12 00:00:00,0,74597,2016-04-07 08:45:19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49959,2016-03-28 21:53:21,Mercedes_Benz_C_180_T_Kompressor_Classic,privat,Angebot,4200.0,control,kombi,2003,manuell,143,c_klasse,150000.0,12,benzin,mercedes_benz,nein,2016-03-28 00:00:00,0,53844,2016-04-07 05:16:23
49962,2016-03-14 17:57:15,Mitsubishi_Space_Star_1__3_L__Bj_2004_Standhei...,privat,Angebot,2200.0,test,limousine,2004,manuell,82,andere,150000.0,4,benzin,mitsubishi,ja,2016-03-14 00:00:00,0,45481,2016-03-15 13:45:08
49963,2016-03-26 19:52:59,Mercedes_Benz_B_200_CDI_Special_Edition,privat,Angebot,7600.0,control,bus,2007,manuell,140,b_klasse,125000.0,5,diesel,mercedes_benz,nein,2016-03-26 00:00:00,0,92272,2016-03-28 09:45:44
49965,2016-03-11 10:53:51,Opel_Astra_1.6_Lenkradheizung~Sitzheizung,privat,Angebot,6700.0,test,limousine,2011,manuell,116,astra,125000.0,3,benzin,opel,nein,2016-03-11 00:00:00,0,37627,2016-03-15 01:44:57
49966,2016-04-02 19:49:19,CitroÃ«n_C1_1.0_**Euro4**TÃœV_OKT_2017**Scheiten...,privat,Angebot,1490.0,control,kleinwagen,2006,manuell,68,c1,150000.0,7,benzin,citroen,ja,2016-04-02 00:00:00,0,26603,2016-04-02 19:49:19
49968,2016-04-01 17:49:15,Mercedes_Benz_190_D_2.5_Automatik,privat,Angebot,2100.0,test,limousine,1986,automatik,90,andere,150000.0,9,diesel,mercedes_benz,nein,2016-04-01 00:00:00,0,40227,2016-04-05 13:16:35
49969,2016-03-17 18:49:02,Nissan_X_Trail_2.2_dCi_4x4_Sport_m.AHZ,privat,Angebot,4500.0,control,suv,2005,manuell,136,x_trail,150000.0,5,diesel,nissan,nein,2016-03-17 00:00:00,0,17379,2016-03-25 23:18:15
49970,2016-03-21 22:47:37,c4_Grand_Picasso_mit_Automatik_Leder_Navi_Temp...,privat,Angebot,15800.0,control,bus,2010,automatik,136,c4,60000.0,4,diesel,citroen,nein,2016-03-21 00:00:00,0,14947,2016-04-07 04:17:34
49971,2016-03-29 14:54:12,W.Lupo_1.0,privat,Angebot,950.0,test,kleinwagen,2001,manuell,50,lupo,150000.0,4,benzin,volkswagen,nein,2016-03-29 00:00:00,0,65197,2016-03-29 20:41:51
49972,2016-03-26 22:25:23,Mercedes_Benz_Vito_115_CDI_Extralang_Aut.,privat,Angebot,3300.0,control,bus,2004,automatik,150,vito,150000.0,10,diesel,mercedes_benz,ja,2016-03-26 00:00:00,0,65326,2016-03-28 11:28:18
49973,2016-03-27 05:32:39,Mercedes_Benz_SLK_200_Kompressor,privat,Angebot,6000.0,control,cabrio,2004,manuell,163,slk,150000.0,11,benzin,mercedes_benz,nein,2016-03-27 00:00:00,0,53567,2016-03-27 08:25:24
49974,2016-03-20 10:52:31,Golf_1_Cabrio_Tuev_Neu_viele_Extras_alles_eing...,privat,Angebot,0.0,control,cabrio,1983,manuell,70,golf,150000.0,2,benzin,volkswagen,nein,2016-03-20 00:00:00,0,8209,2016-03-27 19:48:16
49975,2016-03-27 20:51:39,Honda_Jazz_1.3_DSi_i_VTEC_IMA_CVT_Comfort,privat,Angebot,9700.0,control,kleinwagen,2012,automatik,88,jazz,100000.0,11,hybrid,honda,nein,2016-03-27 00:00:00,0,84385,2016-04-05 19:45:34
49976,2016-03-19 18:56:05,Audi_80_Avant_2.6_E__Vollausstattung!!_Einziga...,privat,Angebot,5900.0,test,kombi,1992,automatik,150,80,150000.0,12,benzin,audi,nein,2016-03-19 00:00:00,0,36100,2016-04-07 06:16:44
49977,2016-03-31 18:37:18,Mercedes_Benz_C200_Cdi_W203,privat,Angebot,5500.0,control,limousine,2003,manuell,116,c_klasse,150000.0,2,diesel,mercedes_benz,nein,2016-03-31 00:00:00,0,33739,2016-04-06 12:16:11
49978,2016-04-04 10:37:14,Mercedes_Benz_E_200_Classic,privat,Angebot,900.0,control,limousine,1996,automatik,136,e_klasse,150000.0,9,benzin,mercedes_benz,ja,2016-04-04 00:00:00,0,24405,2016-04-06 12:44:20
49979,2016-03-20 18:38:40,Volkswagen_Polo_1.6_TDI_Style,privat,Angebot,11000.0,test,kleinwagen,2011,manuell,90,polo,70000.0,11,diesel,volkswagen,nein,2016-03-20 00:00:00,0,48455,2016-04-07 01:45:12
49981,2016-03-15 09:38:21,Opel_Astra_Kombi_mit_Anhaengerkupplung,privat,Angebot,2000.0,control,kombi,1998,manuell,115,astra,150000.0,12,benzin,opel,nein,2016-03-15 00:00:00,0,86859,2016-04-05 17:21:46
49986,2016-04-04 20:46:02,Chrysler_300C_3.0_CRD_DPF_Automatik_Voll_Ausst...,privat,Angebot,15900.0,control,limousine,2010,automatik,218,300c,125000.0,11,diesel,chrysler,nein,2016-04-04 00:00:00,0,73527,2016-04-06 23:16:00
49987,2016-03-22 20:47:27,Audi_A3_Limousine_2.0_TDI_DPF_Ambition__NAVI__...,privat,Angebot,21990.0,control,limousine,2013,manuell,150,a3,50000.0,11,diesel,audi,nein,2016-03-22 00:00:00,0,94362,2016-03-26 22:46:06
49988,2016-03-28 19:49:51,BMW_330_Ci,privat,Angebot,9550.0,control,coupe,2001,manuell,231,3er,150000.0,10,benzin,bmw,nein,2016-03-28 00:00:00,0,83646,2016-04-07 02:17:40
49989,2016-03-11 19:50:37,VW_Polo_zum_Ausschlachten_oder_Wiederaufbau,privat,Angebot,150.0,test,kleinwagen,1997,manuell,0,polo,150000.0,5,benzin,volkswagen,ja,2016-03-11 00:00:00,0,21244,2016-03-12 10:17:55
49990,2016-03-21 19:54:19,Mercedes_Benz_A_200__BlueEFFICIENCY__Urban,privat,Angebot,17500.0,test,limousine,2012,manuell,156,a_klasse,30000.0,12,benzin,mercedes_benz,nein,2016-03-21 00:00:00,0,58239,2016-04-06 22:46:57
49992,2016-03-10 19:37:38,Fiat_Grande_Punto_1.4_T_Jet_16V_Sport,privat,Angebot,4800.0,control,kleinwagen,2009,manuell,120,andere,125000.0,9,lpg,fiat,nein,2016-03-10 00:00:00,0,68642,2016-03-13 01:44:51
49994,2016-03-22 17:36:42,Audi_A6__S6__Avant_4.2_quattro_eventuell_Tausc...,privat,Angebot,5000.0,control,kombi,2001,automatik,299,a6,150000.0,1,benzin,audi,nein,2016-03-22 00:00:00,0,46537,2016-04-06 08:16:39
49995,2016-03-27 14:38:19,Audi_Q5_3.0_TDI_qu._S_tr.__Navi__Panorama__Xenon,privat,Angebot,24900.0,control,limousine,2011,automatik,239,q5,100000.0,1,diesel,audi,nein,2016-03-27 00:00:00,0,82131,2016-04-01 13:47:40
49996,2016-03-28 10:50:25,Opel_Astra_F_Cabrio_Bertone_Edition___TÃœV_neu+...,privat,Angebot,1980.0,control,cabrio,1996,manuell,75,astra,150000.0,5,benzin,opel,nein,2016-03-28 00:00:00,0,44807,2016-04-02 14:18:02
49997,2016-04-02 14:44:48,Fiat_500_C_1.2_Dualogic_Lounge,privat,Angebot,13200.0,test,cabrio,2014,automatik,69,500,5000.0,11,benzin,fiat,nein,2016-04-02 00:00:00,0,73430,2016-04-04 11:47:27
49998,2016-03-08 19:25:42,Audi_A3_2.0_TDI_Sportback_Ambition,privat,Angebot,22900.0,control,kombi,2013,manuell,150,a3,40000.0,11,diesel,audi,nein,2016-03-08 00:00:00,0,35683,2016-04-05 16:45:07
49999,2016-03-14 00:42:12,Opel_Vectra_1.6_16V,privat,Angebot,1250.0,control,limousine,1996,manuell,101,vectra,150000.0,1,benzin,opel,nein,2016-03-13 00:00:00,0,45897,2016-04-06 21:18:48

In [23]:
autos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 20 columns):
date_crawled          50000 non-null object
name                  50000 non-null object
seller                50000 non-null object
offer_type            50000 non-null object
price                 49986 non-null float64
abtest                50000 non-null object
vehicle_type          44905 non-null object
registration_year     50000 non-null int64
gear_box              47320 non-null object
power_ps              50000 non-null int64
model                 47242 non-null object
odometer_km           50000 non-null float64
registration_month    50000 non-null int64
fuel_type             45518 non-null object
brand                 50000 non-null object
unrepaired_damage     40171 non-null object
ad_created            50000 non-null object
nr_of_pictures        50000 non-null int64
postal_code           50000 non-null int64
last_seen             50000 non-null object
dtypes: float64(2), int64(5), object(13)
memory usage: 7.6+ MB

In [24]:
autos.loc[:20,['date_crawled','last_seen','ad_created']]

           date_crawled            last_seen           ad_created
0   2016-03-26 17:47:46  2016-04-06 06:45:54  2016-03-26 00:00:00
1   2016-04-04 13:38:56  2016-04-06 14:45:08  2016-04-04 00:00:00
2   2016-03-26 18:57:24  2016-04-06 20:15:37  2016-03-26 00:00:00
3   2016-03-12 16:58:10  2016-03-15 03:16:28  2016-03-12 00:00:00
4   2016-04-01 14:38:50  2016-04-01 14:38:50  2016-04-01 00:00:00
5   2016-03-21 13:47:45  2016-04-06 09:45:21  2016-03-21 00:00:00
6   2016-03-20 17:55:21  2016-03-23 02:48:59  2016-03-20 00:00:00
7   2016-03-16 18:55:19  2016-04-07 03:17:32  2016-03-16 00:00:00
8   2016-03-22 16:51:34  2016-03-26 18:18:10  2016-03-22 00:00:00
9   2016-03-16 13:47:02  2016-04-06 10:46:35  2016-03-16 00:00:00
10  2016-03-15 01:41:36  2016-04-07 03:16:21  2016-03-14 00:00:00
11  2016-03-16 18:45:34  2016-03-16 18:45:34  2016-03-16 00:00:00
12  2016-03-31 19:48:22  2016-04-06 14:17:52  2016-03-31 00:00:00
13  2016-03-23 10:48:32  2016-04-01 14:17:13  2016-03-23 00:00:00
14  2016-03-23 11:50:46  2016-04-01 15:46:47  2016-03-23 00:00:00
15  2016-04-01 12:06:20  2016-04-02 21:10:48  2016-04-01 00:00:00
16  2016-03-16 14:59:02  2016-03-18 05:29:37  2016-03-16 00:00:00
17  2016-03-29 11:46:22  2016-04-05 20:46:26  2016-03-29 00:00:00
18  2016-03-26 19:57:44  2016-04-02 12:16:41  2016-03-26 00:00:00
19  2016-03-17 13:36:21  2016-03-17 14:45:58  2016-03-17 00:00:00
20  2016-03-05 19:57:31  2016-03-07 05:46:46  2016-03-05 00:00:00

In [25]:
(autos['date_crawled'].str[:10].value_counts(normalize = True,dropna = False).sort_index(ascending = True))

2016-03-05    0.02538
2016-03-06    0.01394
2016-03-07    0.03596
2016-03-08    0.03330
2016-03-09    0.03322
2016-03-10    0.03212
2016-03-11    0.03248
2016-03-12    0.03678
2016-03-13    0.01556
2016-03-14    0.03662
2016-03-15    0.03398
2016-03-16    0.02950
2016-03-17    0.03152
2016-03-18    0.01306
2016-03-19    0.03490
2016-03-20    0.03782
2016-03-21    0.03752
2016-03-22    0.03294
2016-03-23    0.03238
2016-03-24    0.02910
2016-03-25    0.03174
2016-03-26    0.03248
2016-03-27    0.03104
2016-03-28    0.03484
2016-03-29    0.03418
2016-03-30    0.03362
2016-03-31    0.03192
2016-04-01    0.03380
2016-04-02    0.03540
2016-04-03    0.03868
2016-04-04    0.03652
2016-04-05    0.01310
2016-04-06    0.00318
2016-04-07    0.00142
Name: date_crawled, dtype: float64

In [26]:
print('The max and min frequency of date_crawled with dropping Null value')
print(autos['date_crawled'].str[:10].value_counts(normalize = True).max(),end = ' ')
print(autos['date_crawled'].str[:10].value_counts(normalize = True).min())

print('The max and min of date_crawled without dropping null')
print(autos['date_crawled'].str[:10].value_counts(normalize = True, dropna = False).max())
print(autos['date_crawled'].str[:10].value_counts(normalize = True, dropna = False).min())

The max and min frequency of date_crawled with dropping Null value
0.03868 0.00142
The max and min of date_crawled without dropping null
0.03868
0.00142

At the date_crawled min and max value from drop null and no drop null are same, so there are not null value in date_crawled column

In [27]:
autos['last_seen'].str[:10].value_counts(normalize = True, dropna = False).sort_index()

2016-03-05    0.00108
2016-03-06    0.00442
2016-03-07    0.00536
2016-03-08    0.00760
2016-03-09    0.00986
2016-03-10    0.01076
2016-03-11    0.01252
2016-03-12    0.02382
2016-03-13    0.00898
2016-03-14    0.01280
2016-03-15    0.01588
2016-03-16    0.01644
2016-03-17    0.02792
2016-03-18    0.00742
2016-03-19    0.01574
2016-03-20    0.02070
2016-03-21    0.02074
2016-03-22    0.02158
2016-03-23    0.01858
2016-03-24    0.01956
2016-03-25    0.01920
2016-03-26    0.01696
2016-03-27    0.01602
2016-03-28    0.02086
2016-03-29    0.02234
2016-03-30    0.02484
2016-03-31    0.02384
2016-04-01    0.02310
2016-04-02    0.02490
2016-04-03    0.02536
2016-04-04    0.02462
2016-04-05    0.12428
2016-04-06    0.22100
2016-04-07    0.13092
Name: last_seen, dtype: float64

In [28]:
autos['ad_created'].str[:10].value_counts(normalize = True, dropna = False).sort_index(ascending = True)

2015-06-11    0.00002
2015-08-10    0.00002
2015-09-09    0.00002
2015-11-10    0.00002
2015-12-05    0.00002
2015-12-30    0.00002
2016-01-03    0.00002
2016-01-07    0.00002
2016-01-10    0.00004
2016-01-13    0.00002
2016-01-14    0.00002
2016-01-16    0.00002
2016-01-22    0.00002
2016-01-27    0.00006
2016-01-29    0.00002
2016-02-01    0.00002
2016-02-02    0.00004
2016-02-05    0.00004
2016-02-07    0.00002
2016-02-08    0.00002
2016-02-09    0.00004
2016-02-11    0.00002
2016-02-12    0.00006
2016-02-14    0.00004
2016-02-16    0.00002
2016-02-17    0.00002
2016-02-18    0.00004
2016-02-19    0.00006
2016-02-20    0.00004
2016-02-21    0.00006
               ...
2016-03-09    0.03324
2016-03-10    0.03186
2016-03-11    0.03278
2016-03-12    0.03662
2016-03-13    0.01692
2016-03-14    0.03522
2016-03-15    0.03374
2016-03-16    0.03000
2016-03-17    0.03120
2016-03-18    0.01372
2016-03-19    0.03384
2016-03-20    0.03786
2016-03-21    0.03772
2016-03-22    0.03280
2016-03-23    0.03218
2016-03-24    0.02908
2016-03-25    0.03188
2016-03-26    0.03256
2016-03-27    0.03090
2016-03-28    0.03496
2016-03-29    0.03414
2016-03-30    0.03344
2016-03-31    0.03192
2016-04-01    0.03380
2016-04-02    0.03508
2016-04-03    0.03892
2016-04-04    0.03688
2016-04-05    0.01184
2016-04-06    0.00326
2016-04-07    0.00128
Name: ad_created, Length: 76, dtype: float64

In [29]:
autos.loc[((autos['registration_year'] > 2016) | (autos['registration_year'] < 1900)), 'registration_year'] = np.nan

In [30]:
autos.dropna()

,date_crawled,name,seller,offer_type,price,abtest,vehicle_type,registration_year,gear_box,power_ps,model,odometer_km,registration_month,fuel_type,brand,unrepaired_damage,ad_created,nr_of_pictures,postal_code,last_seen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,5000.0,control,bus,2004.0,manuell,158,andere,150000.0,3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,8500.0,control,limousine,1997.0,automatik,286,7er,150000.0,6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,8990.0,test,limousine,2009.0,manuell,102,golf,70000.0,7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,4350.0,control,kleinwagen,2007.0,automatik,71,fortwo,70000.0,6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,privat,Angebot,1350.0,test,kombi,2003.0,manuell,0,focus,150000.0,7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50
7,2016-03-16 18:55:19,Golf_IV_1.9_TDI_90PS,privat,Angebot,1990.0,control,limousine,1998.0,manuell,90,golf,150000.0,12,diesel,volkswagen,nein,2016-03-16 00:00:00,0,53474,2016-04-07 03:17:32
9,2016-03-16 13:47:02,Renault_Megane_Scenic_1.6e_RT_Klimaanlage,privat,Angebot,590.0,control,bus,1997.0,manuell,90,megane,150000.0,7,benzin,renault,nein,2016-03-16 00:00:00,0,15749,2016-04-06 10:46:35
12,2016-03-31 19:48:22,Smart_smart_fortwo_coupe_softouch_pure_MHD_Pan...,privat,Angebot,5299.0,control,kleinwagen,2010.0,automatik,71,fortwo,50000.0,9,benzin,smart,nein,2016-03-31 00:00:00,0,34590,2016-04-06 14:17:52
13,2016-03-23 10:48:32,Audi_A3_1.6_tuning,privat,Angebot,1350.0,control,limousine,1999.0,manuell,101,a3,150000.0,11,benzin,audi,nein,2016-03-23 00:00:00,0,12043,2016-04-01 14:17:13
16,2016-03-16 14:59:02,Opel_Vectra_B_Kombi,privat,Angebot,350.0,test,kombi,1999.0,manuell,101,vectra,150000.0,5,benzin,opel,nein,2016-03-16 00:00:00,0,57299,2016-03-18 05:29:37
17,2016-03-29 11:46:22,Volkswagen_Scirocco_2_G60,privat,Angebot,5500.0,test,coupe,1990.0,manuell,205,scirocco,150000.0,6,benzin,volkswagen,nein,2016-03-29 00:00:00,0,74821,2016-04-05 20:46:26
19,2016-03-17 13:36:21,mazda_tribute_2.0_mit_gas_und_tuev_neu_2018,privat,Angebot,4150.0,control,suv,2004.0,manuell,124,andere,150000.0,2,lpg,mazda,nein,2016-03-17 00:00:00,0,40878,2016-03-17 14:45:58
21,2016-03-06 19:07:10,Porsche_911_Carrera_4S_Cabrio,privat,Angebot,41500.0,test,cabrio,2004.0,manuell,320,911,150000.0,4,benzin,porsche,nein,2016-03-06 00:00:00,0,65428,2016-04-05 23:46:19
22,2016-03-28 20:50:54,MINI_Cooper_S_Cabrio,privat,Angebot,25450.0,control,cabrio,2015.0,manuell,184,cooper,10000.0,1,benzin,mini,nein,2016-03-28 00:00:00,0,44789,2016-04-01 06:45:30
24,2016-04-03 11:57:02,BMW_535i_xDrive_Sport_Aut.,privat,Angebot,48500.0,control,limousine,2014.0,automatik,306,5er,30000.0,12,benzin,bmw,nein,2016-04-03 00:00:00,0,22547,2016-04-07 13:16:50
26,2016-04-03 22:46:28,Volkswagen_Polo_Fox,privat,Angebot,777.0,control,kleinwagen,1992.0,manuell,54,polo,125000.0,2,benzin,volkswagen,nein,2016-04-03 00:00:00,0,38110,2016-04-05 23:46:48
28,2016-03-19 21:56:19,MINI_Cooper_D,privat,Angebot,5250.0,control,kleinwagen,2007.0,manuell,110,cooper,150000.0,7,diesel,mini,ja,2016-03-19 00:00:00,0,15745,2016-04-07 14:58:48
29,2016-04-02 12:45:44,Mercedes_Benz_E_320_T_CDI_Avantgarde_DPF7_Sitz...,privat,Angebot,4999.0,test,kombi,2004.0,automatik,204,e_klasse,150000.0,10,diesel,mercedes_benz,nein,2016-04-02 00:00:00,0,47638,2016-04-02 12:45:44
30,2016-03-14 11:47:31,Peugeot_206_Unfallfahrzeug,privat,Angebot,80.0,test,kleinwagen,2002.0,manuell,60,2_reihe,150000.0,6,benzin,peugeot,ja,2016-03-14 00:00:00,0,57076,2016-03-14 11:47:31
31,2016-03-14 16:53:09,Noch_gut_erhaltenen_C_320,privat,Angebot,2850.0,test,kombi,2002.0,automatik,218,c_klasse,150000.0,7,benzin,mercedes_benz,nein,2016-03-14 00:00:00,0,41065,2016-03-16 07:19:04
33,2016-03-15 12:25:26,Audi_A3_2.0_TDI_Sportback_DPF_Kupplung_defekt_...,privat,Angebot,4800.0,test,kombi,2006.0,manuell,140,a3,150000.0,8,diesel,audi,nein,2016-03-15 00:00:00,0,61169,2016-04-07 13:15:31
35,2016-03-29 21:52:56,Ford_Mondeo,privat,Angebot,1200.0,test,kombi,1998.0,manuell,0,mondeo,150000.0,12,benzin,ford,nein,2016-03-29 00:00:00,0,52428,2016-04-06 08:45:35
36,2016-03-16 23:46:31,Ford_Mondeo_2.0_Turnier_TDCi_DPF_Titanium,privat,Angebot,7500.0,test,kombi,2007.0,manuell,131,mondeo,150000.0,11,diesel,ford,nein,2016-03-16 00:00:00,0,34246,2016-04-05 16:21:16
37,2016-03-23 16:47:46,Seat_Altea_XL_2.0_TDI_CR_DPF_Style,privat,Angebot,13800.0,test,bus,2012.0,manuell,140,altea,90000.0,2,diesel,seat,nein,2016-03-23 00:00:00,0,85113,2016-04-05 20:17:53
38,2016-03-21 15:51:10,Volkswagen_Golf_1.4_Special,privat,Angebot,2850.0,control,limousine,2002.0,manuell,75,golf,125000.0,2,benzin,volkswagen,nein,2016-03-21 00:00:00,0,63674,2016-03-28 12:16:06
39,2016-03-11 13:58:38,Mercedes_C_180_Kombi__zu_verkaufen,privat,Angebot,1450.0,test,kombi,1999.0,automatik,122,c_klasse,150000.0,6,benzin,mercedes_benz,nein,2016-03-11 00:00:00,0,12683,2016-04-06 15:17:52
40,2016-03-07 14:50:03,VW_Golf__4_Cabrio_2.0_GTI_16V___Leder_MFA_Alus...,privat,Angebot,3500.0,control,cabrio,1999.0,manuell,150,golf,150000.0,1,benzin,volkswagen,nein,2016-03-07 00:00:00,0,6780,2016-03-12 02:15:52
43,2016-03-08 16:51:22,Audi_A1_1.2_TFSI_Attraction_mit_Garantie,privat,Angebot,11500.0,test,kleinwagen,2011.0,manuell,86,a1,60000.0,9,benzin,audi,nein,2016-03-08 00:00:00,0,85049,2016-04-07 03:16:05
44,2016-03-12 10:38:06,Zu_verkaufen,privat,Angebot,900.0,control,kleinwagen,1998.0,manuell,43,twingo,150000.0,7,benzin,renault,nein,2016-03-12 00:00:00,0,79725,2016-04-06 01:17:27
45,2016-03-12 17:39:55,Toyota_Starlet_1.3,privat,Angebot,1000.0,test,kleinwagen,1995.0,manuell,75,andere,150000.0,3,benzin,toyota,nein,2016-03-12 00:00:00,0,74597,2016-04-07 08:45:19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49959,2016-03-28 21:53:21,Mercedes_Benz_C_180_T_Kompressor_Classic,privat,Angebot,4200.0,control,kombi,2003.0,manuell,143,c_klasse,150000.0,12,benzin,mercedes_benz,nein,2016-03-28 00:00:00,0,53844,2016-04-07 05:16:23
49962,2016-03-14 17:57:15,Mitsubishi_Space_Star_1__3_L__Bj_2004_Standhei...,privat,Angebot,2200.0,test,limousine,2004.0,manuell,82,andere,150000.0,4,benzin,mitsubishi,ja,2016-03-14 00:00:00,0,45481,2016-03-15 13:45:08
49963,2016-03-26 19:52:59,Mercedes_Benz_B_200_CDI_Special_Edition,privat,Angebot,7600.0,control,bus,2007.0,manuell,140,b_klasse,125000.0,5,diesel,mercedes_benz,nein,2016-03-26 00:00:00,0,92272,2016-03-28 09:45:44
49965,2016-03-11 10:53:51,Opel_Astra_1.6_Lenkradheizung~Sitzheizung,privat,Angebot,6700.0,test,limousine,2011.0,manuell,116,astra,125000.0,3,benzin,opel,nein,2016-03-11 00:00:00,0,37627,2016-03-15 01:44:57
49966,2016-04-02 19:49:19,CitroÃ«n_C1_1.0_**Euro4**TÃœV_OKT_2017**Scheiten...,privat,Angebot,1490.0,control,kleinwagen,2006.0,manuell,68,c1,150000.0,7,benzin,citroen,ja,2016-04-02 00:00:00,0,26603,2016-04-02 19:49:19
49968,2016-04-01 17:49:15,Mercedes_Benz_190_D_2.5_Automatik,privat,Angebot,2100.0,test,limousine,1986.0,automatik,90,andere,150000.0,9,diesel,mercedes_benz,nein,2016-04-01 00:00:00,0,40227,2016-04-05 13:16:35
49969,2016-03-17 18:49:02,Nissan_X_Trail_2.2_dCi_4x4_Sport_m.AHZ,privat,Angebot,4500.0,control,suv,2005.0,manuell,136,x_trail,150000.0,5,diesel,nissan,nein,2016-03-17 00:00:00,0,17379,2016-03-25 23:18:15
49970,2016-03-21 22:47:37,c4_Grand_Picasso_mit_Automatik_Leder_Navi_Temp...,privat,Angebot,15800.0,control,bus,2010.0,automatik,136,c4,60000.0,4,diesel,citroen,nein,2016-03-21 00:00:00,0,14947,2016-04-07 04:17:34
49971,2016-03-29 14:54:12,W.Lupo_1.0,privat,Angebot,950.0,test,kleinwagen,2001.0,manuell,50,lupo,150000.0,4,benzin,volkswagen,nein,2016-03-29 00:00:00,0,65197,2016-03-29 20:41:51
49972,2016-03-26 22:25:23,Mercedes_Benz_Vito_115_CDI_Extralang_Aut.,privat,Angebot,3300.0,control,bus,2004.0,automatik,150,vito,150000.0,10,diesel,mercedes_benz,ja,2016-03-26 00:00:00,0,65326,2016-03-28 11:28:18
49973,2016-03-27 05:32:39,Mercedes_Benz_SLK_200_Kompressor,privat,Angebot,6000.0,control,cabrio,2004.0,manuell,163,slk,150000.0,11,benzin,mercedes_benz,nein,2016-03-27 00:00:00,0,53567,2016-03-27 08:25:24
49974,2016-03-20 10:52:31,Golf_1_Cabrio_Tuev_Neu_viele_Extras_alles_eing...,privat,Angebot,0.0,control,cabrio,1983.0,manuell,70,golf,150000.0,2,benzin,volkswagen,nein,2016-03-20 00:00:00,0,8209,2016-03-27 19:48:16
49975,2016-03-27 20:51:39,Honda_Jazz_1.3_DSi_i_VTEC_IMA_CVT_Comfort,privat,Angebot,9700.0,control,kleinwagen,2012.0,automatik,88,jazz,100000.0,11,hybrid,honda,nein,2016-03-27 00:00:00,0,84385,2016-04-05 19:45:34
49976,2016-03-19 18:56:05,Audi_80_Avant_2.6_E__Vollausstattung!!_Einziga...,privat,Angebot,5900.0,test,kombi,1992.0,automatik,150,80,150000.0,12,benzin,audi,nein,2016-03-19 00:00:00,0,36100,2016-04-07 06:16:44
49977,2016-03-31 18:37:18,Mercedes_Benz_C200_Cdi_W203,privat,Angebot,5500.0,control,limousine,2003.0,manuell,116,c_klasse,150000.0,2,diesel,mercedes_benz,nein,2016-03-31 00:00:00,0,33739,2016-04-06 12:16:11
49978,2016-04-04 10:37:14,Mercedes_Benz_E_200_Classic,privat,Angebot,900.0,control,limousine,1996.0,automatik,136,e_klasse,150000.0,9,benzin,mercedes_benz,ja,2016-04-04 00:00:00,0,24405,2016-04-06 12:44:20
49979,2016-03-20 18:38:40,Volkswagen_Polo_1.6_TDI_Style,privat,Angebot,11000.0,test,kleinwagen,2011.0,manuell,90,polo,70000.0,11,diesel,volkswagen,nein,2016-03-20 00:00:00,0,48455,2016-04-07 01:45:12
49981,2016-03-15 09:38:21,Opel_Astra_Kombi_mit_Anhaengerkupplung,privat,Angebot,2000.0,control,kombi,1998.0,manuell,115,astra,150000.0,12,benzin,opel,nein,2016-03-15 00:00:00,0,86859,2016-04-05 17:21:46
49986,2016-04-04 20:46:02,Chrysler_300C_3.0_CRD_DPF_Automatik_Voll_Ausst...,privat,Angebot,15900.0,control,limousine,2010.0,automatik,218,300c,125000.0,11,diesel,chrysler,nein,2016-04-04 00:00:00,0,73527,2016-04-06 23:16:00
49987,2016-03-22 20:47:27,Audi_A3_Limousine_2.0_TDI_DPF_Ambition__NAVI__...,privat,Angebot,21990.0,control,limousine,2013.0,manuell,150,a3,50000.0,11,diesel,audi,nein,2016-03-22 00:00:00,0,94362,2016-03-26 22:46:06
49988,2016-03-28 19:49:51,BMW_330_Ci,privat,Angebot,9550.0,control,coupe,2001.0,manuell,231,3er,150000.0,10,benzin,bmw,nein,2016-03-28 00:00:00,0,83646,2016-04-07 02:17:40
49989,2016-03-11 19:50:37,VW_Polo_zum_Ausschlachten_oder_Wiederaufbau,privat,Angebot,150.0,test,kleinwagen,1997.0,manuell,0,polo,150000.0,5,benzin,volkswagen,ja,2016-03-11 00:00:00,0,21244,2016-03-12 10:17:55
49990,2016-03-21 19:54:19,Mercedes_Benz_A_200__BlueEFFICIENCY__Urban,privat,Angebot,17500.0,test,limousine,2012.0,manuell,156,a_klasse,30000.0,12,benzin,mercedes_benz,nein,2016-03-21 00:00:00,0,58239,2016-04-06 22:46:57
49992,2016-03-10 19:37:38,Fiat_Grande_Punto_1.4_T_Jet_16V_Sport,privat,Angebot,4800.0,control,kleinwagen,2009.0,manuell,120,andere,125000.0,9,lpg,fiat,nein,2016-03-10 00:00:00,0,68642,2016-03-13 01:44:51
49994,2016-03-22 17:36:42,Audi_A6__S6__Avant_4.2_quattro_eventuell_Tausc...,privat,Angebot,5000.0,control,kombi,2001.0,automatik,299,a6,150000.0,1,benzin,audi,nein,2016-03-22 00:00:00,0,46537,2016-04-06 08:16:39
49995,2016-03-27 14:38:19,Audi_Q5_3.0_TDI_qu._S_tr.__Navi__Panorama__Xenon,privat,Angebot,24900.0,control,limousine,2011.0,automatik,239,q5,100000.0,1,diesel,audi,nein,2016-03-27 00:00:00,0,82131,2016-04-01 13:47:40
49996,2016-03-28 10:50:25,Opel_Astra_F_Cabrio_Bertone_Edition___TÃœV_neu+...,privat,Angebot,1980.0,control,cabrio,1996.0,manuell,75,astra,150000.0,5,benzin,opel,nein,2016-03-28 00:00:00,0,44807,2016-04-02 14:18:02
49997,2016-04-02 14:44:48,Fiat_500_C_1.2_Dualogic_Lounge,privat,Angebot,13200.0,test,cabrio,2014.0,automatik,69,500,5000.0,11,benzin,fiat,nein,2016-04-02 00:00:00,0,73430,2016-04-04 11:47:27
49998,2016-03-08 19:25:42,Audi_A3_2.0_TDI_Sportback_Ambition,privat,Angebot,22900.0,control,kombi,2013.0,manuell,150,a3,40000.0,11,diesel,audi,nein,2016-03-08 00:00:00,0,35683,2016-04-05 16:45:07
49999,2016-03-14 00:42:12,Opel_Vectra_1.6_16V,privat,Angebot,1250.0,control,limousine,1996.0,manuell,101,vectra,150000.0,1,benzin,opel,nein,2016-03-13 00:00:00,0,45897,2016-04-06 21:18:48

In [31]:
autos['registration_year'].value_counts(normalize = True).sort_index(ascending = True)

1910.0    0.000187
1927.0    0.000021
1929.0    0.000021
1931.0    0.000021
1934.0    0.000042
1937.0    0.000083
1938.0    0.000021
1939.0    0.000021
1941.0    0.000042
1943.0    0.000021
1948.0    0.000021
1950.0    0.000062
1951.0    0.000042
1952.0    0.000021
1953.0    0.000021
1954.0    0.000042
1955.0    0.000042
1956.0    0.000104
1957.0    0.000042
1958.0    0.000083
1959.0    0.000146
1960.0    0.000708
1961.0    0.000125
1962.0    0.000083
1963.0    0.000187
1964.0    0.000250
1965.0    0.000354
1966.0    0.000458
1967.0    0.000562
1968.0    0.000541
            ...
1987.0    0.001562
1988.0    0.002957
1989.0    0.003769
1990.0    0.008224
1991.0    0.007412
1992.0    0.008141
1993.0    0.009265
1994.0    0.013742
1995.0    0.027338
1996.0    0.030066
1997.0    0.042225
1998.0    0.051074
1999.0    0.062464
2000.0    0.069834
2001.0    0.056280
2002.0    0.052740
2003.0    0.056779
2004.0    0.056988
2005.0    0.062776
2006.0    0.056384
2007.0    0.047972
2008.0    0.046452
2009.0    0.043683
2010.0    0.033251
2011.0    0.034022
2012.0    0.027546
2013.0    0.016782
2014.0    0.013867
2015.0    0.008308
2016.0    0.027401
Name: registration_year, Length: 78, dtype: float64

In [32]:
max_value = autos['registration_year'].value_counts().max()
dis_regis_year = autos['registration_year'].value_counts()
dis_regis_year[dis_regis_year == max_value].index

Float64Index([2000.0], dtype='float64')

The Top 5 brand

In [33]:
autos['brand'].value_counts(normalize = True)

volkswagen        0.21374
opel              0.10922
bmw               0.10858
mercedes_benz     0.09468
audi              0.08566
ford              0.06958
renault           0.04808
peugeot           0.02912
fiat              0.02616
seat              0.01882
skoda             0.01572
mazda             0.01514
nissan            0.01508
citroen           0.01402
smart             0.01402
toyota            0.01234
sonstige_autos    0.01092
hyundai           0.00976
volvo             0.00914
mini              0.00848
mitsubishi        0.00812
honda             0.00798
kia               0.00712
alfa_romeo        0.00658
porsche           0.00588
suzuki            0.00586
chevrolet         0.00566
chrysler          0.00362
dacia             0.00258
daihatsu          0.00256
jeep              0.00220
subaru            0.00218
land_rover        0.00198
saab              0.00160
daewoo            0.00158
trabant           0.00156
jaguar            0.00154
rover             0.00138
lancia            0.00114
lada              0.00062
Name: brand, dtype: float64

In [34]:
dict_mean_price = {}
for brnd in autos['brand'].value_counts().index[:17]:
    mean = autos.loc[autos['brand'] == brnd, 'price'].mean()
    dict_mean_price[brnd] = mean
sorted_dict_mean = sorted(dict_mean_price.items())

In [35]:
print(dict_mean_price)
print(sorted_dict_mean)

{'toyota': 5097.941653160454, 'nissan': 4588.879310344828, 'volkswagen': 5158.7885623362035, 'renault': 2351.301996672213, 'fiat': 2697.6771231828616, 'mazda': 3962.542932628798, 'peugeot': 3010.8688186813188, 'opel': 2845.914652014652, 'skoda': 6305.044529262086, 'ford': 3626.5429968363533, 'citroen': 3686.657142857143, 'seat': 4219.431455897981, 'bmw': 8026.995394252027, 'mercedes_benz': 8389.942531164166, 'smart': 3482.971469329529, 'audi': 8965.560354891431, 'sonstige_autos': 10538.230202578268}
[('audi', 8965.560354891431), ('bmw', 8026.995394252027), ('citroen', 3686.657142857143), ('fiat', 2697.6771231828616), ('ford', 3626.5429968363533), ('mazda', 3962.542932628798), ('mercedes_benz', 8389.942531164166), ('nissan', 4588.879310344828), ('opel', 2845.914652014652), ('peugeot', 3010.8688186813188), ('renault', 2351.301996672213), ('seat', 4219.431455897981), ('skoda', 6305.044529262086), ('smart', 3482.971469329529), ('sonstige_autos', 10538.230202578268), ('toyota', 5097.941653160454), ('volkswagen', 5158.7885623362035)]

In [36]:
type(sorted_dict_mean)

list

In [37]:
top6_mean_price = {}
top6_mileage = {}
for brnd in sorted_dict_mean[:6]:
    brand = brnd [0]
    average_price = autos.loc[autos['brand'] == brand, 'price'].mean()
    average_mileage = autos.loc[autos['brand'] == brand, 'odometer_km'].mean()
    top6_mean_price[brand] = average_price
    top6_mileage[brand] = average_mileage
print(top6_mean_price)
print(top6_mileage)

{'ford': 3626.5429968363533, 'citroen': 3686.657142857143, 'fiat': 2697.6771231828616, 'mazda': 3962.542932628798, 'audi': 8965.560354891431, 'bmw': 8026.995394252027}
{'ford': 124131.93446392642, 'citroen': 119764.62196861627, 'fiat': 117037.4617737003, 'mazda': 125132.10039630119, 'audi': 129643.9411627364, 'bmw': 132521.64302818198}

In [38]:
series_mean_price = pd.Series(top6_mean_price)
series_mileage = pd.Series(top6_mileage)

In [39]:
print(series_mileage)

audi       129643.941163
bmw        132521.643028
citroen    119764.621969
fiat       117037.461774
ford       124131.934464
mazda      125132.100396
dtype: float64

In [40]:
df = pd.DataFrame(series_mean_price, columns = ['mean_price'])

In [41]:
df['mileage'] = series_mileage

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, audi to mazda
Data columns (total 2 columns):
mean_price    6 non-null float64
mileage       6 non-null float64
dtypes: float64(2)
memory usage: 144.0+ bytes

In [43]:
print(df)

          mean_price        mileage
audi     8965.560355  129643.941163
bmw      8026.995394  132521.643028
citroen  3686.657143  119764.621969
fiat     2697.677123  117037.461774
ford     3626.542997  124131.934464
mazda    3962.542933  125132.100396

In [44]:
autos[:10]

,date_crawled,name,seller,offer_type,price,abtest,vehicle_type,registration_year,gear_box,power_ps,model,odometer_km,registration_month,fuel_type,brand,unrepaired_damage,ad_created,nr_of_pictures,postal_code,last_seen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,5000.0,control,bus,2004.0,manuell,158,andere,150000.0,3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,8500.0,control,limousine,1997.0,automatik,286,7er,150000.0,6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,8990.0,test,limousine,2009.0,manuell,102,golf,70000.0,7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,4350.0,control,kleinwagen,2007.0,automatik,71,fortwo,70000.0,6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,privat,Angebot,1350.0,test,kombi,2003.0,manuell,0,focus,150000.0,7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50
5,2016-03-21 13:47:45,Chrysler_Grand_Voyager_2.8_CRD_Aut.Limited_Sto...,privat,Angebot,7900.0,test,bus,2006.0,automatik,150,voyager,150000.0,4,diesel,chrysler,NaN,2016-03-21 00:00:00,0,22962,2016-04-06 09:45:21
6,2016-03-20 17:55:21,VW_Golf_III_GT_Special_Electronic_Green_Metall...,privat,Angebot,300.0,test,limousine,1995.0,manuell,90,golf,150000.0,8,benzin,volkswagen,NaN,2016-03-20 00:00:00,0,31535,2016-03-23 02:48:59
7,2016-03-16 18:55:19,Golf_IV_1.9_TDI_90PS,privat,Angebot,1990.0,control,limousine,1998.0,manuell,90,golf,150000.0,12,diesel,volkswagen,nein,2016-03-16 00:00:00,0,53474,2016-04-07 03:17:32
8,2016-03-22 16:51:34,Seat_Arosa,privat,Angebot,250.0,test,NaN,2000.0,manuell,0,arosa,150000.0,10,NaN,seat,nein,2016-03-22 00:00:00,0,7426,2016-03-26 18:18:10
9,2016-03-16 13:47:02,Renault_Megane_Scenic_1.6e_RT_Klimaanlage,privat,Angebot,590.0,control,bus,1997.0,manuell,90,megane,150000.0,7,benzin,renault,nein,2016-03-16 00:00:00,0,15749,2016-04-06 10:46:35

In [57]:
autos['date_crawled'] = autos['date_crawled'].str.replace('-','')

In [59]:
autos['date_crawled'] = autos['date_crawled'].astype(int)

In [56]:
autos['ad_created'].str.replace('-','').str[:7].astype(int)

0        2016032
1        2016040
2        2016032
3        2016031
4        2016040
5        2016032
6        2016032
7        2016031
8        2016032
9        2016031
10       2016031
11       2016031
12       2016033
13       2016032
14       2016032
15       2016040
16       2016031
17       2016032
18       2016032
19       2016031
20       2016030
21       2016030
22       2016032
23       2016031
24       2016040
25       2016032
26       2016040
27       2016032
28       2016031
29       2016040
          ...
49970    2016032
49971    2016032
49972    2016032
49973    2016032
49974    2016032
49975    2016032
49976    2016031
49977    2016033
49978    2016040
49979    2016032
49980    2016031
49981    2016031
49982    2016032
49983    2016030
49984    2016033
49985    2016040
49986    2016040
49987    2016032
49988    2016032
49989    2016031
49990    2016032
49991    2016030
49992    2016031
49993    2016031
49994    2016032
49995    2016032
49996    2016032
49997    2016040
49998    2016030
49999    2016031
Name: ad_created, Length: 50000, dtype: int64

In [61]:
autos['brand'].value_counts(normalize = True)

volkswagen        0.21374
opel              0.10922
bmw               0.10858
mercedes_benz     0.09468
audi              0.08566
ford              0.06958
renault           0.04808
peugeot           0.02912
fiat              0.02616
seat              0.01882
skoda             0.01572
mazda             0.01514
nissan            0.01508
citroen           0.01402
smart             0.01402
toyota            0.01234
sonstige_autos    0.01092
hyundai           0.00976
volvo             0.00914
mini              0.00848
mitsubishi        0.00812
honda             0.00798
kia               0.00712
alfa_romeo        0.00658
porsche           0.00588
suzuki            0.00586
chevrolet         0.00566
chrysler          0.00362
dacia             0.00258
daihatsu          0.00256
jeep              0.00220
subaru            0.00218
land_rover        0.00198
saab              0.00160
daewoo            0.00158
trabant           0.00156
jaguar            0.00154
rover             0.00138
lancia            0.00114
lada              0.00062
Name: brand, dtype: float64

In [84]:
list_combine = {}
for brand in autos['brand'].value_counts().index[:5]:
    model =autos.loc[autos['brand'] == brand, 'model'].value_counts()
    list_combine[brand] = model

In [85]:
list_combine

{'audi': a4        1291
 a3         882
 a6         835
 andere     220
 80         218
 tt         149
 a5         127
 a1          84
 a8          75
 q5          62
 100         60
 a2          46
 q7          42
 q3          28
 90           9
 200          1
 Name: model, dtype: int64, 'bmw': 3er        2761
 5er        1183
 1er         538
 x_reihe     302
 7er         135
 z_reihe     121
 m_reihe      47
 andere       42
 6er          32
 i3            1
 Name: model, dtype: int64, 'mercedes_benz': c_klasse    1172
 e_klasse    1001
 a_klasse     588
 andere       446
 clk          255
 slk          172
 m_klasse     154
 s_klasse     135
 vito         127
 b_klasse     126
 sprinter     103
 sl           102
 viano         64
 cl            41
 glk           30
 g_klasse      25
 v_klasse      25
 gl            12
 Name: model, dtype: int64, 'opel': corsa       1735
 astra       1454
 vectra       574
 zafira       423
 omega        202
 andere       157
 meriva       147
 tigra         96
 insignia      88
 signum        69
 agila         62
 vivaro        57
 combo         56
 kadett        53
 calibra       26
 antara        22
 Name: model, dtype: int64, 'volkswagen': golf           4024
 polo           1757
 passat         1425
 transporter     704
 touran          468
 lupo            349
 sharan          233
 caddy           225
 beetle          132
 tiguan          121
 bora            105
 touareg          98
 andere           98
 fox              90
 scirocco         89
 eos              67
 kaefer           63
 up               52
 jetta            39
 phaeton          32
 cc               20
 amarok            7
 Name: model, dtype: int64}

In [81]:
autos['brand'].value_counts().index[:10]

Index(['volkswagen', 'opel', 'bmw', 'mercedes_benz', 'audi', 'ford', 'renault',
       'peugeot', 'fiat', 'seat'],
      dtype='object')